---
- name: Install DHCP,DNSPrimary
  hosts: serverPrincipal
  become: yes
  vars:
    #dhcp y base de datos
    db_name: kea_lease_db
    db_user: kea
    db_pass: admin
    kea_conf_template: kea-dhcp4.conf.j2


    #DNS  
    dns_domain: "reikiavik.xyz"
    zone_file: "db.{{ dns_domain }}"
    zone_file_path: "/etc/bind/zones/{{ zone_file }}"
    primary_ip: "192.168.88.170" #Servidor primario
    secondary_ip: "192.168.88.171" #Servidor secundario
    webserver_ip: "192.168.88.200" #Web server
    clientnetwork: "192.168.88.0/24" #Red de en la cual se puede consultar el dns
    soa_email: "admin.reikiavik.xyz.com."
    reverse_zone: "88.168.192.in-addr.arpa"
    reverse_zone_file: "db.192"
    reverse_zone_file_path: "/etc/bind/zones/{{ reverse_zone_file }}"
    
    #NTP
    redCliente: 192.168.88.0 

    records:
      - { name: "ns1", type: "A", ip: "{{ primary_ip }}" }
      - { name: "ns2", type: "A", ip: "{{ secondary_ip }}" }
      - { name: "www", type: "A", ip: "{{ webserver_ip }}" }
    reverse_records:
      - { ip_last: "11", ptr: "ns1.reikiavik.xyz." }
      - { ip_last: "10", ptr: "ns2.reikiavik.xyz." }
      - { ip_last: "200", ptr: "www.reikiavik.xyz."}
    zones:
      - name: "{{ dns_domain }}"
        type: "master"
        file: "{{ zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_zone }}"
        type: "master"
        file: "{{ reverse_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"

  roles:
    - ntpServer
    - dhcp
    - dnsPrimary

- name: Install DNSsecundary
  hosts: serverSecundario
  become: yes
  vars:
       #DNS
    dns_domain: "reikiavik.xyz"
    zone_file: "db.{{ dns_domain }}"
    zone_file_path: "/etc/bind/zones/{{ zone_file }}"
    primary_ip: "192.168.88.170" #Servidor primario
    secondary_ip: "192.168.88.171" #Servidor secundario
    webserver_ip: "192.168.88.200" #Web server
    clientnetwork: "192.168.88.0/24" #Red de en la cual se puede consultar el dns
    soa_email: "admin.reikiavik.xyz.com."
    reverse_zone: "88.168.192.in-addr.arpa"
    reverse_zone_file: "db.192"
    reverse_zone_file_path: "/etc/bind/zones/{{ reverse_zone_file }}"

    records:
      - { name: "ns1", type: "A", ip: "{{ primary_ip }}" }
      - { name: "ns2", type: "A", ip: "{{ secondary_ip }}" }
      - { name: "www", type: "A", ip: "{{ webserver_ip }}" }
    reverse_records:
      - { ip_last: "11", ptr: "ns1.reikiavik.xyz." }
      - { ip_last: "10", ptr: "ns2.reikiavik.xyz." }
      - { ip_last: "200", ptr: "www.reikiavik.xyz."}
    zones:
      - name: "{{ dns_domain }}"
        type: "master"
        file: "{{ zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_zone }}"
        type: "master"
        file: "{{ reverse_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
  roles:
      - dnsSecundary
      - ntpCliente


