---
- name: Install DHCP,DNSPrimary
  hosts: serverPrincipal
  become: yes
  vars:
    #dhcp y base de datos
    db_name: kea_lease_db
    db_user: kea
    db_pass: admin
    kea_conf_template: kea-dhcp4.conf.j2
    #DNS  
    dns_domain: "reikiavik.xyz"
    zone_file: "db.{{ dns_domain }}"
    zone_file_path: "/etc/bind/zones/{{ zone_file }}"
    primary_ip: "192.168.88.170" #Servidor primario
    primary_ip_ipv6: "2001:db8:1::100"
    secondary_ip: "192.168.88.171" #Servidor secundario
    secondary_ip_ipv6: "2001:db8:1::101"
    webserver_ip: "192.168.88.202" #Web server
    clientnetwork: "192.168.88.0/24" #Red de en la cual se puede consultar el dns
    smptServer: "192.168.88.173"
    soa_email: "admin.reikiavik.com."
    reverse_zone: "88.168.192.in-addr.arpa"
    reverse_zone_file: "db.192"
    reverse_zone_file_path: "/etc/bind/zones/{{ reverse_zone_file }}"
    reverse_ipv6_zone: "0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa"
    reverse_ipv6_zone_file: "db.ipv6"
    reverse_ipv6_zone_file_path: "/etc/bind/zones/{{ reverse_ipv6_zone_file }}"
    
    #NTP
    redCliente: 192.168.88.0 

    records:
      - { name: "ns1", type: "A", ip: "{{ primary_ip }}" }
      - { name: "ns1", type: "AAAA", ip: "{{primary_ip_ipv6}}" }
      - { name: "ns2", type: "A", ip: "{{ secondary_ip }}" }
      - { name: "ns2", type: "AAAA", ip: "{{ secondary_ip_ipv6 }}" }
      - { name: "www", type: "A", ip: "{{ webserver_ip }}" }
      - { name: "mail", type: "A", ip: "{{ smptServer }}" } #Tipo A para el servidor de correos
      - { name: "@", type: "MX", priority: 10, value: "mail.{{dns_domain}}." } #MX que referencia al mail de arriba 
      - { name: "@", type: "TXT", value: "\"v=spf1 ip4:{{ smptServer }} ~all\"" } #TXT spf = servidores que pueden enviar correo
      - { name: "default._domainkey", type: "TXT", value: "\"v=DKIM1; k=rsa; p=CLAVE_PUBLICA_DKIM\"" } #DKIM para cartografia de los correos que se envían
      - { name: "_dmarc", type: "TXT", value: "\"v=DMARC1; p=none; rua=mailto:postmaster@{{dns_domain}}\"" } #DMARC para definir qu hacer con los correos que no pasen dkim ni spf 

    reverse_records:
      - { ip_last: "170", ptr: "ns1.reikiavik.xyz." }
      - { ip_last: "171", ptr: "ns2.reikiavik.xyz." }
      - { ip_last: "202", ptr: "web.reikiavik.xyz."}

    reverse_ipv6_records:
      - { reverse: "0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2", ptr: "ns1.reikiavik.xyz." }
      - { reverse: "1.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2", ptr: "ns2.reikiavik.xyz." }
    zones:
      - name: "{{ dns_domain }}"
        type: "master"
        file: "{{ zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_zone }}"
        type: "master"
        file: "{{ reverse_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_ipv6_zone }}"
        type: "master"
        file: "{{ reverse_ipv6_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
  roles:
    - ntpServer
    - dhcp
    - dnsPrimary

- name: Install DNSsecundary
  hosts: serverSecundario
  become: yes
  vars:
       #DNS
    dns_domain: "reikiavik.xyz"
    zone_file: "db.{{ dns_domain }}"
    zone_file_path: "/etc/bind/zones/{{ zone_file }}"
    primary_ip: "192.168.88.170" #Servidor primario
    secondary_ip: "192.168.88.171" #Servidor secundario
    secondary_ip_ipv6: "2001:db8:1::101"
    webserver_ip: "192.168.88.202" #Web server
    clientnetwork: "192.168.88.0/24" #Red de en la cual se puede consultar el dns
    smptServer: "192.168.88.173"
    soa_email: "admin.reikiavik.xyz.com."
    reverse_zone: "88.168.192.in-addr.arpa"
    reverse_zone_file: "db.192"
    reverse_zone_file_path: "/etc/bind/zones/{{ reverse_zone_file }}"
    reverse_ipv6_zone: "0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa"
    reverse_ipv6_zone_file: "db.ipv6"
    reverse_ipv6_zone_file_path: "/etc/bind/zones/{{ reverse_ipv6_zone_file }}"
    records:
      - { name: "ns1", type: "A", ip: "{{ primary_ip }}" }
      - { name: "ns2", type: "A", ip: "{{ secondary_ip }}" }
      - { name: "www", type: "A", ip: "{{ webserver_ip }}" }
    reverse_records:
      - { ip_last: "170", ptr: "ns1.reikiavik.xyz." }
      - { ip_last: "171", ptr: "ns2.reikiavik.xyz." }
      - { ip_last: "202", ptr: "www.reikiavik.xyz."}
    reverse_ipv6_records:
      - { reverse: "0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2", ptr: "ns1.reikiavik.xyz." }
      - { reverse: "1.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.0.0.2", ptr: "ns2.reikiavik.xyz." }
       
    zones:
      - name: "{{ dns_domain }}"
        type: "master"
        file: "{{ zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_zone }}"
        type: "master"
        file: "{{ reverse_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
      - name: "{{ reverse_ipv6_zone }}"
        type: "master"
        file: "{{ reverse_ipv6_zone_file_path }}"
        allow_transfer: "{{ secondary_ip }}"
  roles:
      - dnsSecundary
      - ntpCliente
