---
- name: Instalar BIND9
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: Asegurar que el directorio de claves exista
  file:
    path: /etc/bind/keys
    state: directory
    owner: bind
    group: bind
    mode: '0750'

- name: Asegurar que el directorio de zonas exista
  file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: '0755'

- name: Configurar named.conf.local con zonas esclavas
  template:
    src: confinamelocalsec.j2
    dest: "/etc/bind/named.conf.local"
    owner: root
    group: bind
    mode: '0644'

- name: Verificar que la configuración de BIND no tenga errores
  command: named-checkconf
  register: named_check
  failed_when: named_check.rc != 0
  changed_when: false

- name: Reiniciar servicio bind9
  service:
    name: bind9
    state: restarted
    enabled: yes

- name: Ejecutar retransfer de zonas
  command: "rndc retransfer {{ item.name }}"
  loop: "{{ zones }}"

