---
    - name: Instalar MariaDB server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Instalar Kea-admin
      apt:
        name: kea-admin
        state: present
        update_cache: yes
    
    - name: Crear base de datos para Kea
      mysql_db:
        name: kea_lease_db
        state: present
        collation: utf8_general_ci
        encoding: utf8
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: true

    - name: Crear usuario kea y asignar permisos
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{db_name}}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: true

   
    - name: Dar permisos globales
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "*.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: true

    
    - name: Install Kea DHCP server
      apt:
        name: kea-dhcp4-server
        state: present
        update_cache: yes

    - name: Copy Kea DHCP configuration file
      template:
        src: kea-dhcp4.conf.j2
        dest: /etc/kea/kea-dhcp4.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start kea-dhcp4 service
      systemd:
        name: kea-dhcp4-server
        enabled: yes
        state: restarted

    - name: Ejecutar kea-admin db-init
      command: >
        kea-admin db-init mysql -u {{ db_user }} -p {{ db_pass }} -n {{ db_name }}
      args:
        creates: /var/lib/kea/kea-dhcp4.csv

    - name: Ajustar parámetros en my.cnf
      blockinfile:
        path: /etc/mysql/my.cnf
        block: |
          [mysqld]
          innodb_flush_log_at_trx_commit=2

    - name: Reiniciar MariaDB
      service:
        name: mysql
        state: restarted

    - name: Reiniciar y habilitar Kea DHCP
      systemd:
        name: kea-dhcp4-server
        enabled: yes
        state: restarted
